services:
  - type: web
    name: islap-frontend
    env: static
    staticPublishPath: frontend/build

  - type: web
    name: islap-backend
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      python backend/data/xml_to_sqlite.py
    startCommand: uvicorn backend.api.main:app --host 0.0.0.0
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7