services:
  - type: web
    name: islap-frontend
    env: static
    staticPublishPath: build

  - type: web
    name: islap-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.api.main:app --host 0.0.0.0 --port 10000
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7